// This file was auto-generated by Fern from our API Definition.

/**
 * Anam Avatar configuration parameters.
 */
export interface AnamAvatarParams {
    /** Anam API key. */
    api_key: string;
    /** The unique identifier for the Anam avatar you want to use. */
    avatar_id: string;
    /** The unique identifier for the avatar's RTC connection. This must be different from other participants in the channel. */
    agora_uid: string;
    /** The RTC token that authorizes the avatar to join the video channel. */
    agora_token: string;
    /** The audio sample rate in Hz. */
    sample_rate?: number;
    /** The video quality level. */
    quality?: AnamAvatarParams.Quality;
    /** The video encoding format. */
    video_encoding?: AnamAvatarParams.VideoEncoding;
    /** Anam avatar model, such as `cara_mk4` for Cara 4 portrait mode. */
    avatar_model?: string;
    /** Anam output video width in pixels. Set together with `video_height`; omit both to use the model default resolution. */
    video_width?: number;
    /** Anam output video height in pixels. Set together with `video_width`; omit both to use the model default resolution. */
    video_height?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace AnamAvatarParams {
    /** The video quality level. */
    export const Quality = {
        High: "high",
        Medium: "medium",
        Low: "low",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
    /** The video encoding format. */
    export const VideoEncoding = {
        H264: "H264",
        Av1: "AV1",
    } as const;
    export type VideoEncoding = (typeof VideoEncoding)[keyof typeof VideoEncoding];
}
