// This file was auto-generated by Fern from our API Definition.

/**
 * Gemini TTS configuration parameters.
 */
export interface GeminiTtsParams {
    /** Gemini API key. */
    api_key: string;
    /** Gemini TTS model name. */
    model: string;
    /** Gemini voice name. */
    voice: string;
    /** Style instruction for the generated speech. */
    style?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
