// This file was auto-generated by Fern from our API Definition.

export interface McpServer {
    /** A unique identifier for the MCP server. Maximum 48 characters. Accepts only English letters and numbers. */
    name: string;
    /** The endpoint address of the MCP server. The agent uses this to communicate with the MCP server. */
    endpoint: string;
    /**
     * Transport protocol type.
     * - `streamable_http`: Streaming HTTP protocol
     */
    transport?: "streamable_http";
    /** HTTP header information to include when requesting the MCP server, such as authentication information. */
    headers?: Record<string, string>;
    /**
     * A list of tools that the agent is allowed to invoke. The agent can only use tools on this list.
     * - Empty or omitted: All tools are enabled.
     * - Empty array `[]`: No tools are enabled.
     * - `["*"]`: All tools are enabled.
     * - Specific tools `["aa", "bb"]`: Only listed tools are enabled.
     * - Mix with wildcard `["aa", "*"]`: All tools are enabled (wildcard takes precedence).
     */
    allowed_tools?: string[];
    /** The MCP server request timeout in milliseconds. After timeout, the agent stops waiting for the MCP server's response and continues executing subsequent logic. */
    timeout_ms?: number;
}
