// This file was auto-generated by Fern from our API Definition.

/**
 * Tool interface exposed to the model. `parameters` defines LLM arguments, not the HTTP request shape.
 */
export interface RestToolFunction {
    /** Function name visible to the model. Used as the REST tool index key (ASCII case-insensitive). */
    name: string;
    /** Function description visible to the model. */
    description?: string;
    /** JSON Schema defining the LLM tool-call arguments (`args`). Must be an object schema with `type: object` and `properties`. */
    parameters: RestToolFunction.Parameters;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace RestToolFunction {
    /**
     * JSON Schema defining the LLM tool-call arguments (`args`). Must be an object schema with `type: object` and `properties`.
     */
    export interface Parameters {
        /** JSON Schema type. Must be `object`. */
        type: "object";
        /** Argument property definitions keyed by argument name. */
        properties: Record<string, unknown>;
        /** List of required argument names. */
        required?: string[];
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
