// This file was auto-generated by Fern from our API Definition.

/**
 * Tool execution configuration. Defaults to `{"mode": "sync"}`. Phase 1a only allows `sync`.
 */
export interface RestToolExecution {
    /** Execution mode. Phase 1a only accepts `sync`. */
    mode?: "sync";
    /** Accepts any additional properties */
    [key: string]: any;
}
