// This file was auto-generated by Fern from our API Definition.

/**
 * Actual HTTP request configuration for this REST tool.
 * Does not use top-level `parameters`, `path_params`, standalone `query`,
 * `response`, `json_path`, or `max_chars`.
 */
export interface RestToolServer {
    /** HTTP method. Must be `GET` or `POST`. */
    method: RestToolServer.Method;
    /**
     * Full request URL. Write path and query templates directly in the URL.
     * Placeholders allowed: `{{args.<name>}}`, `{{template_variables.<name>}}`,
     * and `{{tool_call_id}}`. URL values may be string, number, or boolean.
     */
    url: string;
    /**
     * Request headers as a string dictionary.
     * Each header value must be a constant or exactly one placeholder.
     * Placeholders allowed: `{{template_variables.<name>}}` and `{{tool_call_id}}`.
     * `{{args.*}}` is not allowed in headers.
     */
    headers?: Record<string, string>;
    /**
     * POST JSON body template. Must not be configured for `GET` requests.
     * Supports arbitrary nested JSON. Only fields declared in `server.body` are sent.
     * Leaf values may be constants or exactly one of `{{args.<name>}}`,
     * `{{template_variables.<name>}}`, or `{{tool_call_id}}`.
     * JSON body preserves original types after rendering.
     */
    body?: Record<string, unknown>;
    /** Request timeout in milliseconds. Defaults to `10000`. Valid range is `1000` to `100000`. */
    timeout_ms?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace RestToolServer {
    /** HTTP method. Must be `GET` or `POST`. */
    export const Method = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
