// This file was auto-generated by Fern from our API Definition.

/**
 * RTZR ASR configuration parameters.
 */
export interface RtzrAsrParams {
    /** RTZR client ID. */
    client_id: string;
    /** RTZR client secret. */
    client_secret: string;
    /** RTZR API base URL. */
    api_base?: string;
    /** RTZR recognition model name. */
    model_name?: string;
    /** RTZR recognition language code. Defaults to Korean (`ko`). */
    language?: string;
    /** Input audio sample rate in Hz. */
    sample_rate?: number;
    /** Input audio encoding. */
    encoding?: string;
    /** Whether to enable inverse text normalization. */
    use_itn?: boolean;
    /** Whether to filter disfluencies such as stuttering. */
    use_disfluency_filter?: boolean;
    /** Whether to filter profanity. */
    use_profanity_filter?: boolean;
    /** Whether to add punctuation to the recognized text. */
    use_punctuation?: boolean;
    /** Keywords to improve recognition accuracy. */
    keywords?: string[];
    /** Accepts any additional properties */
    [key: string]: any;
}
