// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * RTZR ASR configuration.
 */
export interface RtzrAsr {
    language?: Agora.AsrLanguage;
    params: Agora.RtzrAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
