// This file was auto-generated by Fern from our API Definition.

/**
 * Sarvam TTS configuration parameters.
 */
export interface SarvamTtsParams {
    /** Sarvam API subscription key */
    api_subscription_key: string;
    /** Speaker voice to use. */
    speaker: string;
    /** Target language code in BCP-47 format (e.g., `hi-IN`, `bn-IN`, `en-IN`). */
    target_language_code: SarvamTtsParams.TargetLanguageCode;
    /** Pitch control for the `bulbul:v2` model. */
    pitch?: number;
    /** Speech speed. Defaults to `1.0`. */
    pace?: number;
    /** Audio loudness control for the `bulbul:v2` model. */
    loudness?: number;
    /** Output speech sample rate in Hz. Defaults to `24000`. */
    speech_sample_rate?: number;
    /** Whether to normalize English words and numeric entities. Defaults to `false`. */
    enable_preprocessing?: boolean;
    /** TTS model to use. Defaults to `bulbul:v3`. */
    model?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace SarvamTtsParams {
    /** Target language code in BCP-47 format (e.g., `hi-IN`, `bn-IN`, `en-IN`). */
    export const TargetLanguageCode = {
        EnIn: "en-IN",
        HiIn: "hi-IN",
        BnIn: "bn-IN",
        TaIn: "ta-IN",
        TeIn: "te-IN",
        KnIn: "kn-IN",
        MlIn: "ml-IN",
        MrIn: "mr-IN",
        GuIn: "gu-IN",
        PaIn: "pa-IN",
        OrIn: "or-IN",
    } as const;
    export type TargetLanguageCode = (typeof TargetLanguageCode)[keyof typeof TargetLanguageCode];
}
