// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Smallest AI ASR configuration.
 */
export interface SmallestAiAsr {
    /** Language code for speech recognition. */
    language?: string;
    params: Agora.SmallestAiAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
