// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Smallest AI Text-to-Speech configuration.
 */
export interface SmallestAiTts {
    params: Agora.SmallestAiTtsParams;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
