// This file was auto-generated by Fern from our API Definition.

/**
 * Smallest AI ASR configuration parameters.
 */
export interface SmallestAiAsrParams {
    /** Language code for speech recognition. This takes precedence over the top-level `asr.language` value. */
    language?: string;
    /** WebSocket endpoint for the Smallest AI streaming STT API. */
    url?: string;
    /** Smallest AI API key. */
    api_key: string;
    /** Input audio sample rate in Hz. */
    sample_rate?: number;
    /** Input audio encoding. */
    encoding?: string;
    /** Whether to include word-level timestamps. */
    word_timestamps?: string;
    /** Whether to include sentence-level timestamps. */
    sentence_timestamps?: string;
    /** Whether to enable speaker diarization. */
    diarize?: string;
    /** Whether to return voice activity detection events. */
    vad_events?: string;
    /** Whether to enable endpoint detection. */
    endpointing?: string;
    /** End-of-utterance timeout in milliseconds. */
    eou_timeout_ms?: number;
    /** Whether to format the transcript. */
    format?: string;
    /** Whether to finalize results based on recognized words. */
    finalize_on_words?: string;
    /** Maximum number of words per result. */
    max_words?: string;
    /** Whether to add punctuation. */
    punctuate?: string;
    /** Whether to capitalize transcript text. */
    capitalize?: string;
    /** Whether to enable inverse text normalization. */
    itn_normalize?: string;
    /** Whether to return the full transcript. */
    full_transcript?: string;
    /** Comma-separated keyword boosts in `keyword:weight` format. */
    keywords?: string;
    /** Whether to redact personally identifiable information. */
    redact_pii?: string;
    /** Whether to redact payment card information. */
    redact_pci?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
