// This file was auto-generated by Fern from our API Definition.

/**
 * Smallest AI TTS configuration parameters.
 */
export interface SmallestAiTtsParams {
    /** HTTP endpoint for the Smallest AI streaming TTS API. */
    url?: string;
    /** Smallest AI API key. */
    api_key: string;
    /** Smallest AI TTS model name. */
    model?: string;
    /** Smallest AI voice identifier. */
    voice_id?: string;
    /** Output audio sample rate in Hz. */
    sample_rate?: number;
    /** Speech rate multiplier. */
    speed?: number;
    /** Language code for speech synthesis. */
    language?: string;
    /** Language used to pronounce numbers. */
    number_pronunciation_language?: string;
    /** Whether to verbalize mathematical notation. */
    math_notation?: boolean;
    /** Pronunciation dictionaries applied during synthesis. */
    pronunciation_dicts?: string[];
    /** Client-provided session identifier. */
    session_id?: string;
    /** Client-provided request identifier. */
    request_id?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
