// This file was auto-generated by Fern from our API Definition.

/**
 * Speechmatics ASR configuration parameters.
 */
interface SpeechmaticsAsrParamsBase {
    /** Language code to use for transcription */
    language: string;
    /** WebSocket URL for the Speechmatics streaming API */
    uri?: string | null;
    /** Accepts any additional properties */
    [key: string]: any;
}

export type SpeechmaticsAsrParams = SpeechmaticsAsrParamsBase &
    (
        | {
              /** Speechmatics API key */
              key: string;
              /** @deprecated Use `key` instead. The client normalizes this alias to `key`. */
              api_key?: string;
          }
        | {
              key?: undefined;
              /** @deprecated Use `key` instead. The client normalizes this alias to `key`. */
              api_key: string;
          }
    );
