/**
 * Redaction for `debug: true` session logging.
 *
 * The debug dump is routinely pasted into issues and chat threads, so it must
 * never carry a usable credential. The generated fetcher redacts headers, query
 * params, and URLs, but nothing redacts the request body — which is where
 * vendor API keys and RTC tokens live.
 *
 * Uses the same `[REDACTED]` marker as `core/fetcher/Fetcher.ts` for
 * consistency, but is deliberately independent of it: that file is generated by
 * Fern and its helpers are module-local.
 */

/** Marker substituted for a redacted value. Matches the generated fetcher. */
export const REDACTED = "[REDACTED]";

/**
 * Body fields whose values are credentials or account identifiers.
 *
 * Compared case-insensitively, and matched on both snake_case and camelCase
 * spellings so this keeps working if a caller hand-builds a config.
 */
const SENSITIVE_BODY_KEYS: ReadonlySet<string> = new Set([
    // Vendor credentials
    "api_key",
    "apikey",
    "key",
    "secret",
    "api_secret",
    "apisecret",
    "password",
    "access_key_id",
    "accesskeyid",
    "secret_access_key",
    "secretaccesskey",
    "adc_credentials_string",
    "adccredentialsstring",
    "credentials",
    "subscription_key",
    "subscriptionkey",
    // Agora credentials and account identifiers
    "token",
    "agora_token",
    "agoratoken",
    "authorization",
    "appid",
    "app_id",
    "agora_appid",
    "agoraappid",
    "app_certificate",
    "appcertificate",
    "customer_secret",
    "customersecret",
]);

function isSensitiveKey(key: string): boolean {
    return SENSITIVE_BODY_KEYS.has(key.toLowerCase());
}

function redactQueryKeys(value: string): string {
    let parsed: URL;
    try {
        parsed = new URL(value);
    } catch {
        return value;
    }
    let changed = false;
    for (const key of [...parsed.searchParams.keys()]) {
        if (key.toLowerCase() !== "key") {
            continue;
        }
        const current = parsed.searchParams.getAll(key);
        if (current.some((item) => item.length > 0)) {
            parsed.searchParams.delete(key);
            for (const item of current) {
                parsed.searchParams.append(key, item.length > 0 ? REDACTED : item);
            }
            changed = true;
        }
    }
    return changed ? parsed.toString() : value;
}

/**
 * Deep-copies `value`, replacing credential fields with {@link REDACTED}.
 *
 * Empty strings are left visible on purpose: `""` is the signature of an unset
 * environment variable, and hiding it behind `[REDACTED]` would disguise the
 * exact misconfiguration the debug output exists to surface.
 *
 * Never mutates the input — the request that goes on the wire is untouched.
 */
export function redactSecrets(value: unknown): unknown {
    if (Array.isArray(value)) {
        return value.map((item) => redactSecrets(item));
    }
    if (value === null || typeof value !== "object") {
        return value;
    }

    const result: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value as Record<string, unknown>)) {
        if (isSensitiveKey(key) && typeof item === "string" && item.length > 0) {
            result[key] = REDACTED;
        } else if (typeof item === "string") {
            result[key] = redactQueryKeys(item);
        } else {
            result[key] = redactSecrets(item);
        }
    }
    return result;
}

/**
 * Redacts request headers for debug logging.
 *
 * Non-authorization headers are kept. The authorization credential is removed,
 * while its scheme name stays visible so the active auth mode can be diagnosed.
 */
export function redactHeadersForDebug(headers: Record<string, string>): Record<string, string> {
    const result: Record<string, string> = {};
    for (const [key, value] of Object.entries(headers)) {
        if (key.toLowerCase() !== "authorization") {
            result[key] = value;
            continue;
        }
        const scheme = value.split(/[\s=]/, 1)[0];
        result[key] = scheme && scheme !== value ? `${scheme} ${REDACTED}` : REDACTED;
    }
    return result;
}
